version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./output:/app/output
      - ${DOWNLOADS_DIR:-~/Downloads}:/app/Downloads
      - ${RESEARCH_DIR:-~/Desktop/Research}:/app/Research
    environment:
      - DOWNLOAD_DIR=/app/Downloads
      - RESEARCH_DIR=/app/Research
    restart: "no"
